spring:
  application:
    name: gateway-service
  profiles:
    active: dev

server:
    port: 9090
    servlet:
      contextPath: /gateway-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

  zuul:
    routes:
      searchservice:
        path: /search-service/**
        serviceId: search-service
      restfulservice:
        path: /restful-service/**
        serviceId: restful-service

# later on use logback or log4j2.xml to customise, also have separate folder for each service
# like var/log/{myservicename}/myservicename-{date}.log
logging:
  #file: /var/log/${spring.application.name}.log
  file: C:/Users/saudas1/Documents/backup/AWS/logs/${spring.application.name}.log