spring:
  application:
    name: gateway-service
  profiles:
    active: dev

server:
    port: 9090


eureka:
  instance:
    preferIPAddress: true
    leaseRenewalIntervalInSeconds: 3
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
ribbon:
  eureka:
    enabled: true

  zuul:
    ignoredServices: '*'
    routes:
      search-service:
        path: /search/**
        serviceId: search-service
      restful-service:
        path: /restful/**
        serviceId: restful-service
        strip-prefix: false

# later on use logback or log4j2.xml to customise, also have separate folder for each service
# like var/log/{myservicename}/myservicename-{date}.log
logging:
  #file: /var/log/${spring.application.name}.log
  file: C:/Users/saudas1/Documents/backup/AWS/logs/${spring.application.name}.log
#  level:
#    org.springframework.cloud: DEBUG
#    com.netflix: DEBUG

