spring:
  application:
    name: restful-service
  profiles:
    active: dev

server:
  port: 8091


eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
    leaseRenewalIntervalInSeconds: 3
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

ribbon:
  eureka:
    enabled: true