spring:
  application:
    name: restful-service
  profiles:
    active: dev

server:
  port: 8091
  servlet:
    contextPath: /restful-service

eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost